const data = [
  "Arabian food near me",
  "Bakery food near me",
  "Beverages food near me",
  "Biryani food near me",
  "Chinese food near me",
  "Continental food near me",
  "Burger food near me",
  "Desserts food near me",
  "Ice Cream food near me",
  "Italian food near me",
  "Juices food near me",
  "Kerala food near me",
  "Lebanese food near me",
  "North Indian food near me",
  "Pizza food near me",
  "Seafood food near me",
  "Shake food near me",
  "Shawarma food near me",
  "South Indian food near me",
  "Street food near me me",
];
export default data;
